version: '3.8'

services:
  # https-portal:
  #   container_name: ${SERVICE_NAME}_https_portal_${SERVICE_TYPE}
  #   image: steveltn/https-portal:1
  #   ports:
  #     - ${FRONT_HTTP_PORT}:80
  #     - ${FRONT_HTTPS_PORT}:443
  #   # restart: always
  #   environment:
  #     STAGE: local
  #     DOMAINS: 'localhost -> http://front'

  # front:
  #   container_name: ${SERVICE_NAME}_front_${SERVICE_TYPE}
  #   image: nginx
  #   working_dir: /app
  #   # restart: always
  #   volumes:
  #     - ./src/front/dist:/var/www/html
  #     - ./src/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  api:
    container_name: ${SERVICE_NAME}_api_${SERVICE_TYPE}
    build: ./src/api
    working_dir: /app
    ports:
      - ${API_PORT}:8000
    command: sh main.sh
    volumes:
      - ./src/api/src:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_BACKEND_URL=redis://redis:6379/1

  celery:
    container_name: ${SERVICE_NAME}_celery_${SERVICE_TYPE}
    build: ./src/celery
    command: celery --app=tasks worker --loglevel=info
    volumes:
      - ./src/celery/src:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_BACKEND_URL=redis://redis:6379/1
  # flower:
  #   container_name: ${SERVICE_NAME}_flower_${SERVICE_TYPE}
  #   build: ./src/celery
  #   command: celery --app=tasks flower --loglevel=info
  #   environment:
  #     - BROKER_URL=amqp://guest:guest@rabbitmq:5672/0
  #     - RESULT_BACKEND=redis://redis:6379/0
  #   ports:
  #     - "5555:5555"

  rabbitmq:
    container_name: ${SERVICE_NAME}_rabbitmq_${SERVICE_TYPE}
    image: rabbitmq:latest
    ports:
        - "5672:5672"
    volumes:
        - "./src/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf"
  redis:
    container_name: ${SERVICE_NAME}_redis_${SERVICE_TYPE}
    image: redis:latest
    volumes:
      - redis_db:/data

volumes:
  redis_db:
    driver: local

networks:
  default:
    external:
      name: ${SERVICE_NAME}_${SERVICE_TYPE}
